# Generated by Django 4.0 on 2022-03-30 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 30), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registrationDate',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 30), null=True),
        ),
        migrations.AlterField(
            model_name='staffwork',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 30), null=True),
        ),
    ]
