# Generated by Django 4.0 on 2022-01-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.customer'),
        ),
    ]
