# Generated by Django 4.0 on 2022-03-31 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bill_qr_code_alter_rate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 31), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registrationDate',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 31), null=True),
        ),
        migrations.AlterField(
            model_name='staffwork',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 31), null=True),
        ),
    ]
