# Generated by Django 4.0 on 2022-03-31 11:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rate_date_alter_staff_registrationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to=main.models.upload_to),
        ),
    ]
