# Generated by Django 4.0 on 2022-01-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.customer'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rate', models.IntegerField(null=True)),
                ('customerProductWeight', models.IntegerField(null=True)),
                ('customerProductAmount', models.IntegerField(null=True)),
                ('totalAmount', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('grandTotalAmount', models.IntegerField(null=True)),
                ('advanceAmount', models.IntegerField(null=True)),
                ('payedAmount', models.IntegerField(null=True)),
                ('remainingAmount', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted')], default='Submitted', max_length=11)),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerBill', to='main.customer')),
                ('orderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerOrder', to='main.order')),
            ],
        ),
    ]
