# Generated by Django 4.0 on 2022-03-31 11:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
