# Generated by Django 4.0 on 2022-01-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bill_customerid_alter_bill_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='advanceAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customerProductAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customerProductWeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='grandTotalAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payedAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remainingAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='totalAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='advanceAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='submittedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='submittionDate',
            field=models.DateField(blank=True),
        ),
    ]
