# Generated by Django 4.0 on 2022-01-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bill_advanceamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('netWeight', models.FloatField()),
                ('size', models.FloatField()),
                ('gemsName', models.CharField(blank=True, max_length=50, null=True)),
                ('gemsPrice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('orderProductId', models.AutoField(primary_key=True, serialize=False)),
                ('totalWeight', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Submitted')], default='Pending', max_length=11)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('billProductId', models.AutoField(primary_key=True, serialize=False)),
                ('lossWeight', models.FloatField(blank=True, null=True)),
                ('totalWeight', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('makingCharge', models.FloatField(blank=True, null=True)),
                ('totalAmountPerProduct', models.FloatField(blank=True, null=True)),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='main.bill')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product')),
            ],
        ),
    ]
