# Generated by Django 4.0 on 2022-01-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bill_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproduct',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product'),
        ),
    ]
