# Generated by Django 4.0 on 2022-01-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bill_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.order'),
        ),
    ]
