# Generated by Django 4.0 on 2022-01-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_bill_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted')], default='Submitted', max_length=11),
        ),
        migrations.AlterField(
            model_name='billproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Submitted')], default='Pending', max_length=11),
        ),
    ]
