# Generated by Django 4.0 on 2022-01-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_bill_status_alter_billproduct_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='orderId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.order'),
        ),
    ]
