# Generated by Django 4.0 on 2022-01-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_bill_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproduct',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='main.product'),
        ),
    ]
