# Generated by Django 4.0 on 2022-01-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_bill_orderid_alter_billproduct_billid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproduct',
            name='billId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billProduct', to='main.bill'),
        ),
    ]
