# Generated by Django 4.0 on 2022-01-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_billproduct_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproduct',
            name='productId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product'),
        ),
    ]
