# Generated by Django 4.0 on 2022-01-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_billproduct_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproduct',
            name='productId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='main.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='main.product'),
        ),
    ]
