# Generated by Django 4.0 on 2022-01-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_billproduct_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='orderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='main.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='main.product'),
        ),
    ]
