# Generated by Django 4.0 on 2022-01-09 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_orderproduct_orderid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rateId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hallmarkRate', models.FloatField()),
                ('tajabiRate', models.FloatField()),
                ('silverRate', models.FloatField()),
            ],
        ),
    ]
