# Generated by Django 4.0 on 2022-01-09 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 9, 14, 15, 57, 905389), null=True),
        ),
    ]
