# Generated by Django 4.0 on 2022-01-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_rate_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
