# Generated by Django 4.0 on 2022-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_delete_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rateId', models.AutoField(primary_key=True, serialize=False)),
                ('hallmarkRate', models.FloatField()),
                ('tajabiRate', models.FloatField()),
                ('silverRate', models.FloatField()),
            ],
        ),
    ]
