# Generated by Django 4.0 on 2022-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
