# Generated by Django 4.0 on 2022-01-09 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 9, 15, 0, 1, 743031, tzinfo=utc), null=True),
        ),
    ]
