# Generated by Django 4.0 on 2022-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproduct',
            name='qualtity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
