# Generated by Django 4.0 on 2022-01-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billproduct',
            old_name='qualtity',
            new_name='quantity',
        ),
    ]
