# Generated by Django 4.0 on 2022-01-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_bill_billtype_bill_finalweight_bill_grandweight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='grandWeight',
            new_name='grandTotalWeight',
        ),
    ]
