# Generated by Django 4.0 on 2022-01-30 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_grandweight_bill_grandtotalweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 30), null=True),
        ),
    ]
