# Generated by Django 4.0 on 2022-02-09 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_rate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.AddField(
            model_name='order',
            name='billType',
            field=models.CharField(choices=[('gold', 'GOLD'), ('silver', 'SILVER')], default='gold', max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='customerProductWeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('inprogress', 'INPROGRESS'), ('submitted', 'SUBMITTED')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 9), null=True),
        ),
    ]
