# Generated by Django 4.0 on 2022-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_orderproduct_design_orderproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
