# Generated by Django 4.0 on 2022-02-10 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_orderproduct_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billType',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 10), null=True),
        ),
    ]
