# Generated by Django 4.0 on 2022-02-11 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_billtype_order_type_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customerProductWeight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 11), null=True),
        ),
    ]
