# Generated by Django 4.0 on 2022-02-12 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_bill_customerproductweight_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 12), null=True),
        ),
    ]
