# Generated by Django 4.0 on 2022-02-15 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_order_status_alter_orderproduct_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(blank=True, default=datetime.date(2022, 2, 15), null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 15), null=True),
        ),
        migrations.CreateModel(
            name='StaffWork',
            fields=[
                ('staff_work_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.date(2022, 2, 15), null=True)),
                ('given_weight', models.FloatField()),
                ('KDM_weight', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('submittion_date', models.DateField(blank=True, null=True)),
                ('submitted_weight', models.FloatField(blank=True)),
                ('final_product_weight', models.FloatField(blank=True)),
                ('loss_weight', models.FloatField(blank=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('orderProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='main.orderproduct')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main.staff')),
            ],
        ),
    ]
