# Generated by Django 4.0 on 2022-02-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_staff_alter_rate_date_staffwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='registration_date',
            new_name='registrationDate',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='resign_date',
            new_name='resignDate',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='staffName',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='KDM_weight',
            new_name='KDMWeight',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='final_product_weight',
            new_name='finalProductWeight',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='given_weight',
            new_name='givenWeight',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='loss_weight',
            new_name='lossWeight',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='staff_work_id',
            new_name='staffWorkId',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='submitted_date',
            new_name='submittedDate',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='submitted_weight',
            new_name='submittedWeight',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='submittion_date',
            new_name='submittionDate',
        ),
        migrations.RenameField(
            model_name='staffwork',
            old_name='total_weight',
            new_name='totalWeight',
        ),
    ]
