# Generated by Django 4.0 on 2022-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_staffwork_finalproductweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffwork',
            name='status',
            field=models.CharField(choices=[('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], default='inprogress', max_length=11),
        ),
    ]
