# Generated by Django 4.0 on 2022-03-24 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 24), null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registrationDate',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 24), null=True),
        ),
        migrations.AlterField(
            model_name='staffwork',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 24), null=True),
        ),
    ]
